22q11-ibbc/22q11-ibbc/urls.py
# Core Django imports
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

# Third-party app imports

# Local app imports
from .views import About, Announcement, Contact, Home, Member_Site, Publication

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # public area
    url(r'^$', '22q11-ibbc.views.Home', name='index'),
    url(r'^home/$', '22q11-ibbc.views.Home', name='home'),
    url(r'^about/$', '22q11-ibbc.views.About', name='about'),
    url(r'^annoucement/', '22q11-ibbc.views.Announcement', name='announcement'),
    url(r'^contact/', '22q11-ibbc.views.Contact', name='contact'),
    url(r'^member_site/$', '22q11-ibbc.views.Member_Site', name='member_site'),
    url(r'^publication/$', '22q11-ibbc.views.Publication', name='publication'),

    # private area
    url(r'^data/', include('data.urls', namespace='data')),
)

# Uncomment the next line to serve media files in dev.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

22q11-ibbc/data/urls.py
# Core Django imports
from django.conf.urls import patterns, include, url

# Third-party app imports

# Local app imports
from .views import home
from .views import site_detail_view, affymetrix_folder_download
from .views import UserProfile_DetailView
from .views import Subject_all_ListView, subject_search_view, Subject_search_ListView, Subject_site_ListView, Subject_DetailView
from .views import Affymetrix_all_ListView, affymetrix_search_view, Affymetrix_search_ListView, Affymetrix_site_ListView, Affymetrix_DetailView, affymetrix_download
from .views import wgs, wgs_download
from .views import Documents_1, Documents_2, Documents_3, Documents_4, Documents_5
from .views import logout_view
from .views import reset, reset_confirm, reset_complete

urlpatterns = patterns('',
    # Home
    url(r'^$', 'data.views.home', name='home'),

    # Site
    url(r'^site/(?P<pk>\d+)/$', site_detail_view, name='site_detail'),
    url(r'^site/download/(\S+)/(\S+)/$', affymetrix_folder_download , name='affymetrix_folder_download'),

    # UserProfile
    url(r'^user-profile/(?P<pk>\d+)/$', UserProfile_DetailView.as_view(), name='user_profile_detail'),

    # Subject
    url(r'^subject/list/$', Subject_all_ListView.as_view(), name='subject_all_list'),
    url(r'^subject/list/search/$', subject_search_view, name='subject_search'),
    url(r'^subject/list/(?P<g>[\w ]+)/(?P<l>[\w ]+)/(?P<a>[\w ]+)/(?P<s>[\w ]+)/$', Subject_search_ListView.as_view(), name='subject_search_list'),
    url(r'^subject/list/(?P<pk>\d+)/$', Subject_site_ListView.as_view(), name='subject_site_list'),
    url(r'^subject/(?P<pk>\d+)/$', Subject_DetailView.as_view(), name='subject_detail'),

    # Affymetrix
    url(r'^affymetrix/list/$', Affymetrix_all_ListView.as_view(), name='affymetrix_all_list'),
    url(r'^affymetrix/list/search/$', affymetrix_search_view, name='affymetrix_search'),
    url(r'^affymetrix/list/(?P<a>[\w ]+)/$', Affymetrix_search_ListView.as_view(), name='affymetrix_search_list'),
    url(r'^affymetrix/list/(?P<pk>\d+)/$', Affymetrix_site_ListView.as_view(), name='affymetrix_site_list'),
    url(r'^affymetrix/(?P<pk>\d+)/$', Affymetrix_DetailView.as_view(), name='affymetrix_detail'),
    url(r'^affymetrix/(?P<pk>\d+)/download/$', affymetrix_download , name='affymetrix_download'),

    # WGS
    url(r'^wgs/$', 'data.views.wgs', name='wgs'),
    url(r'^wgs/download/(\S+)/$', wgs_download , name='wgs_download'),

    # Documents
    url(r'^documents_1/$', 'data.views.Documents_1', name='documents_1'),
    url(r'^documents_2/$', 'data.views.Documents_2', name='documents_2'),
    url(r'^documents_3/$', 'data.views.Documents_3', name='documents_3'),
    url(r'^documents_4/$', 'data.views.Documents_4', name='documents_4'),
    url(r'^documents_5/$', 'data.views.Documents_5', name='documents_5'),

    # log on/off
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'data/data_login.html'}, name='22q11_ibbc_login'),
    url(r'^logout/$', logout_view, name='22q11_ibbc_logout'),

    # password reset
    url(r'^reset/$', reset, name='reset'),
    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', reset_confirm, name='reset_confirm'),
    url(r'^reset/complete/$', reset_complete, name='reset_complete'),
)

22q11-ibbc/templates/base_arcana.html
<!DOCTYPE html>
<!--
	Arcana by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>

<!-- HEAD -->
<head>

    <title>{% block title %}{% endblock title %}</title>
    
    <!-- CSS Style -->
    {% load staticfiles %}
    {% block extrastyle %}
    <link rel="icon" type="image/x-icon" href="{% static "images/ibbc.ico" %}" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="{% static "assets/js/ie/html5shiv.js" %}"></script><![endif]-->
    <link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
    <!--[if lte IE 8]><link rel="stylesheet" href="{% static "assets/css/ie8.css" %}" /><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="{% static "assets/css/ie9.css" %}" /><![endif]-->
    {% endblock extrastyle %}
    <!-- End CSS Style -->

</head>
<!-- End HEAD -->

<!-- BODY -->
<body>
    <div id="page-wrapper">

        <!-- Header -->
        <div id="header">

            <!-- Logo -->
            <img src="{% static "images/logo_two.png" %}" width="323" height="100" />
            <h1><a href="{% url 'home' %}" id="logo"><em>International</em> 22q11.2 <em>Brain Behavior Consortium</em></a></h1>
            <!-- END Logo -->

            <!-- Nav -->
            <nav id="nav">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
					<li>|</li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'announcement' %}">Announcements</a></li>
                    <li><a href="{% url 'contact' %}">Contacts</a></li>
                    <li><a href="{% url 'member_site' %}">Member Sites</a></li>
                    <li><a href="{% url 'publication' %}">Publications</a></li>
					<li>|</li>
                    <li>
                        <a href="{% url 'data:home' %}">For Researchers</a>
                        <ul>
                            <li><a href="{% url 'data:home' %}">Data</a></li>
                            <li><a href="{% url 'data:documents_1' %}">Documents</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- END Nav -->

        </div>
        <!-- END Header -->

        <!-- CONTENT -->
        {% block content %}{% endblock content %}
        <!-- END CONTENT -->
    
        <!-- Footer -->
        <div id="footer">

            <!-- Copyright -->
            <div class="copyright">
                <ul class="menu">
                    <li>&copy; 2015 - 2016 Department of Genetics, Albert Einstein College of Medicine, Bronx NY USA. All rights reserved</li>
                    <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                </ul>
            </div>
            <!-- END Copyright -->

        </div>
        <!-- END Footer -->

    </div>

    <!-- Scripts -->
    <script src="{% static "assets/js/jquery.min.js" %}"></script>
    <script src="{% static "assets/js/jquery.dropotron.min.js" %}"></script>
    <script src="{% static "assets/js/skel.min.js" %}"></script>
    <script src="{% static "assets/js/util.js" %}"></script>
    <!--[if lte IE 8]><script src="{% static "assets/js/ie/respond.min.js" %}"></script><![endif]-->
    <script src="{% static "assets/js/main.js" %}"></script>
    {% block scripts %}{% endblock scripts %}
    <!-- END Scripts -->

</body>
</html>

22q11-ibbc/templates/base_private.html
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>

<!-- HEAD -->
<head>
<title>{% block title %}{% endblock title %}</title>

    <!-- CSS Style -->
    {% load staticfiles %}
    {% block extrastyle %}
    <link rel="icon" type="image/x-icon" href="{% static "images/ibbc.ico" %}" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static "css/reset.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/base_private.css" %}" />
    {% endblock extrastyle %}
    <!-- End CSS Style -->

</head>
<!-- End HEAD -->

<!-- BODY -->
<body>

<!-- FULLWIDTHSTRIPE -->
<div id="fullWidthStripe"></div>

<!-- CONTAINER -->
<div id="container">

    <!-- HEADER -->
    <div id="header">
        <!-- LOGO -->
        <div id="logo"><a href="{% url 'home' %}"><img src="{% static "images/logo_one.png" %}" width="323" height="118" /></a></div>
        <div align="center"><h3>MEMBERS ONLY AREA</h3></div>
    </div>
    <!-- END HEADER -->
    
    <!-- NAVIGATION -->
    <ul class="mainNav">
        <li><a href="{% url 'home' %}">Public Area</a></li>
        <li class="nav-separator">|</li>
        <li><a href="{% url 'data:home' %}">Data</a></li>
        <li class="nav-separator">|</li>
        <li><a href="{% url 'data:documents_1' %}">Documents</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-separator">|</li>
        <li><a id="logout" href="{% url 'data:22q11_ibbc_logout' %}">logout</a></li>
        {% endif %}
    </ul>
    <!-- End NAVIGATION -->
    
    <!-- CONTENT -->
    <div id="content">
        {% if messages %}
            {% for message in messages %}
                <div id="dialog" title="Error">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock content %}
    </div>
    <!-- END CONTENT -->

    <!-- FOOTER -->
    <div id="footer">
        <p id="footer-copy">&copy; 2015 - 2016 Department of Genetics, Albert Einstein College of Medicine, Bronx NY USA</p>
    </div>
    <!-- End FOOTER -->

</div>
<!-- END Container -->

</body>
<!-- END BODY -->

</html>

<!-- Scripts -->
<div id="scripts">
<script type="text/javascript">
$(function() {
    $( "#dialog" ).dialog();
});
</script>
{% block scripts %}{% endblock scripts %}
</div>
<!-- END Scripts -->