22q11-ibbc/22q11-ibbc/urls.py
# Core Django imports
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

# Third-party app imports

# Local app imports
from .views import About, Announcement, Contact, Home, Member_Site, Publication

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # public area
    url(r'^$', '22q11-ibbc.views.Home', name='index'),
    url(r'^home/$', '22q11-ibbc.views.Home', name='home'),
    url(r'^about/$', '22q11-ibbc.views.About', name='about'),
    url(r'^annoucement/', '22q11-ibbc.views.Announcement', name='announcement'),
    url(r'^contact/', '22q11-ibbc.views.Contact', name='contact'),
    url(r'^member_site/$', '22q11-ibbc.views.Member_Site', name='member_site'),
    url(r'^publication/$', '22q11-ibbc.views.Publication', name='publication'),

    # private area
    url(r'^data/', include('data.urls', namespace='data')),
)

# Uncomment the next line to serve media files in dev.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

22q11-ibbc/data/urls.py
# Core Django imports
from django.conf.urls import patterns, include, url

# Third-party app imports

# Local app imports
from .views import home
from .views import site_detail_view, affymetrix_folder_download
from .views import UserProfile_DetailView
from .views import Subject_all_ListView, subject_search_view, Subject_search_ListView, Subject_site_ListView, Subject_DetailView
from .views import Affymetrix_all_ListView, affymetrix_search_view, Affymetrix_search_ListView, Affymetrix_site_ListView, Affymetrix_DetailView, affymetrix_download
from .views import wgs, wgs_download
from .views import Documents_1, Documents_2, Documents_3, Documents_4, Documents_5
from .views import logout_view
from .views import reset, reset_confirm, reset_complete

urlpatterns = patterns('',
    # Home
    url(r'^$', 'data.views.home', name='home'),

    # Site
    url(r'^site/(?P<pk>\d+)/$', site_detail_view, name='site_detail'),
    url(r'^site/download/(\S+)/(\S+)/$', affymetrix_folder_download , name='affymetrix_folder_download'),

    # UserProfile
    url(r'^user-profile/(?P<pk>\d+)/$', UserProfile_DetailView.as_view(), name='user_profile_detail'),

    # Subject
    url(r'^subject/list/$', Subject_all_ListView.as_view(), name='subject_all_list'),
    url(r'^subject/list/search/$', subject_search_view, name='subject_search'),
    url(r'^subject/list/(?P<g>[\w ]+)/(?P<l>[\w ]+)/(?P<a>[\w ]+)/(?P<s>[\w ]+)/$', Subject_search_ListView.as_view(), name='subject_search_list'),
    url(r'^subject/list/(?P<pk>\d+)/$', Subject_site_ListView.as_view(), name='subject_site_list'),
    url(r'^subject/(?P<pk>\d+)/$', Subject_DetailView.as_view(), name='subject_detail'),

    # Affymetrix
    url(r'^affymetrix/list/$', Affymetrix_all_ListView.as_view(), name='affymetrix_all_list'),
    url(r'^affymetrix/list/search/$', affymetrix_search_view, name='affymetrix_search'),
    url(r'^affymetrix/list/(?P<a>[\w ]+)/$', Affymetrix_search_ListView.as_view(), name='affymetrix_search_list'),
    url(r'^affymetrix/list/(?P<pk>\d+)/$', Affymetrix_site_ListView.as_view(), name='affymetrix_site_list'),
    url(r'^affymetrix/(?P<pk>\d+)/$', Affymetrix_DetailView.as_view(), name='affymetrix_detail'),
    url(r'^affymetrix/(?P<pk>\d+)/download/$', affymetrix_download , name='affymetrix_download'),

    # WGS
    url(r'^wgs/$', 'data.views.wgs', name='wgs'),
    url(r'^wgs/download/(\S+)/$', wgs_download , name='wgs_download'),

    # Documents
    url(r'^documents_1/$', 'data.views.Documents_1', name='documents_1'),
    url(r'^documents_2/$', 'data.views.Documents_2', name='documents_2'),
    url(r'^documents_3/$', 'data.views.Documents_3', name='documents_3'),
    url(r'^documents_4/$', 'data.views.Documents_4', name='documents_4'),
    url(r'^documents_5/$', 'data.views.Documents_5', name='documents_5'),

    # log on/off
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'data/data_login.html'}, name='22q11_ibbc_login'),
    url(r'^logout/$', logout_view, name='22q11_ibbc_logout'),

    # password reset
    url(r'^reset/$', reset, name='reset'),
    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', reset_confirm, name='reset_confirm'),
    url(r'^reset/complete/$', reset_complete, name='reset_complete'),
)

22q11-ibbc/data/models.py
# Core Django imports
from django.contrib.auth.models import User
from django.db import models

# Third-party app imports

# Local app imports

######################################################################################################
##  Site
######################################################################################################
"""
 Class to hold Site information
"""
class Site(models.Model):
    name = models.CharField(max_length=255, null=False, unique=True)
    group = models.CharField(max_length=255, blank=True)
    folder = models.CharField(max_length=255, null=True, blank=True)
    #Relationships
    site_pis = models.ManyToManyField(User, null=False, blank=True, related_name="%(app_label)s_%(class)s_site_pis")
    site_members = models.ManyToManyField(User, blank=True, related_name="%(app_label)s_%(class)s_site_members")
    allowed_users = models.ManyToManyField(User, blank=True, related_name="%(app_label)s_%(class)s_allowed_users")

    def __unicode__(self):
        return u"""{name}""".format(
            name=self.name,
        )

    def check_site_pis(self, username):
        if self.site_pis.filter(username=username).exists():
            return True
        return False

    def check_site_members(self, username):
        if self.site_members.filter(username=username).exists():
            return True
        return False

    def check_allowed_members(self, username):
        if self.allowed_members.filter(username=username).exists():
            return True
        return False


######################################################################################################
##  User Profile
######################################################################################################
"""
 Class to hold User Role information
"""
class UserRole(models.Model):
    role = models.CharField(max_length=255, blank=True)

    def __unicode__(self):
        return u"""{role}""".format(
            role=self.role,
        )

"""
 Class to hold User Profile information
"""
class UserProfile(models.Model):
    #Relationships
    user = models.ForeignKey(User, null=False, related_name="%(app_label)s_%(class)s_user")
    user_roles = models.ManyToManyField(UserRole, null=False, blank=True, related_name="%(app_label)s_%(class)s_user_roles")

    def __unicode__(self):
        return u"""{name}""".format(
            name=self.user,
        )


#####################################################################################################
#  Subject
#####################################################################################################
"""
 Class to hold Subject information
"""
class Subject(models.Model):
    genomic_db_id = models.IntegerField(primary_key=True)
    site_id = models.CharField(max_length=255, null=False, blank=False)
    alias = models.CharField(max_length=255, null=True, blank=True)
    project = models.CharField(max_length=255, null=True, blank=True)
    #Relationships
    owner_site = models.ForeignKey(Site, null=False, related_name="%(app_label)s_%(class)s_owner_site")

    def __unicode__(self):
        return u"""{genomic_db_id}""".format(
            genomic_db_id=self.genomic_db_id,
        )

    def get_absolute_url(self):
        return reverse('data:subject_detail', kwargs={'pk': self.genomic_db_id})

#####################################################################################################
#  Affymetrix
#####################################################################################################
"""
 Class to hold Affymetrix information
"""
class Affymetrix(models.Model):
    name = models.CharField(max_length=255, null=False, unique=True)
    cel_file = models.FileField(upload_to='.')
    #Relationships
    subject = models.ForeignKey(Subject, null=False, related_name="%(app_label)s_%(class)s_subject")

    def __unicode__(self):
        return u"""{name}""".format(
            name=self.name,
        )

    def get_absolute_url(self):
        return reverse('data:affymetrix_detail', kwargs={'pk': self.id})

22q11-ibbc/data/forms.py
# Core Django imports
from django import forms
from django.forms import Form, ModelForm
from django.core.exceptions import ObjectDoesNotExist

# Third-party app imports

# Local app imports
from .models import Site

#####################################################################################################
#  Subject
"""
Class to hold SubjectListForm information
"""
class SubjectListForm(Form):
    genomic_db_id = forms.CharField(max_length=255, required=False)
    local_id = forms.CharField(max_length=255, required=False)
    alias = forms.CharField(max_length=255, required=False)
    site = forms.ChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        super(SubjectListForm, self).__init__(*args, **kwargs)

        self.fields['genomic_db_id'].initial = '0'
        self.fields['local_id'].initial = 'all'
        self.fields['alias'].initial = 'all'

        sites = Site.objects.values_list('id', 'name').order_by('name').distinct('name')
        site_choices = []
        site_choices.insert(0, ('all', 'all'))
        for site in sites:
            site_choices.append([site[0], site[1]])
        self.fields['site'].choices = site_choices

#####################################################################################################
#  Affymetrix
"""
Class to hold AffymetrixListForm information
"""
class AffymetrixListForm(Form):
    affymetrix_name = forms.CharField(max_length=255, required=False)

    def __init__(self, *args, **kwargs):
        super(AffymetrixListForm, self).__init__(*args, **kwargs)

        self.fields['affymetrix_name'].initial = 'all'

22q11-ibbc/templates/data/data_affymetrix_list_form_search.html
{% extends "data/data_base.html" %}

<!-- CONTENT-DATA-CONTENT- -->
{% block content-data-content %}
    <div id='data-box'>
        <div id='data-box-top'></div>
        <div id='data-box-title'>Search affymetrix</div>

        <form method="post" action="">
            {% csrf_token %}
            <table id='form-detail-table'>
            <tbody>
                <tr>
                    <th>Affymetrix Name:</th>
                    <td><input id="id_affymetrix_name" maxlength="50" name="affymetrix_name" type="text" value="{{ form.affymetrix_name.value|default_if_none:"" }}"/></td>
                </tr>
                <tr>
                    <th></th>
                    <td><input id='form-submit' type="submit" value="Submit" /></td>
                </tr>    
                <tr>
                    <th></th>
                    <td><a href="{% url 'data:subject_search' %}">Cancel</a></td>
                </tr>
            </tbody>
            </table>
        </form>

    </div>
{% endblock %}
<!-- END CONTENT -->

22q11-ibbc/templates/data/data_affymetrix_list_search.html
{% extends "data/data_base.html" %}

<!-- CONTENT-DATA-CONTENT- -->
{% block content-data-content %}
    <div id='data-box'>
        <div id='data-box-top'></div>
        <div id='data-box-title'>Affymetrix Data</div>

        <table>
            <tr>
                <th>Affymetrix Name</th>
                <th>Download</th>
            </tr>
            {% for affymetrix in affymetrix_list %}
            <tr>
                <td id="tag-name-summary"><a href="{% url "data:affymetrix_detail" affymetrix.pk %}"> {{ affymetrix.name }} </a></td>
                <td id="tag-value"><a href="{% url "data:affymetrix_download" affymetrix.pk %}"> Download </a></td>
            </tr>
            {% empty %}
            <tr>
                <td id="tag-name"> Nothing found... </td>
            </tr>
            {% endfor %}
        </table>

        <table>
            <tr>
                <td>
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                
                            <span class="current">
                                Page {{ page_obj.number }} of {{ paginator.num_pages }}
                            </span>
                
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                </td>
            </tr>
        </table>
        <form action="{% url 'data:affymetrix_search_list' a %}">
            <div class="page-search">
                <input type="number" name="page" min="1" max="{{ paginator.num_pages }}" value="{{ page }}">
                <input id='form-submit' type="submit" value="GO" />                                        
            </div>
        </form>
        <div id="hidden-line-bottom"></div>

    </div>
{% endblock %}
<!-- END CONTENT -->

22q11-ibbc/templates/data/data_affymetrix_list_site.html
{% extends "data/data_base.html" %}

<!-- CONTENT-DATA-CONTENT- -->
{% block content-data-content %}
    <div id='data-box'>
        <div id='data-box-top'></div>
        <div id='data-box-title'>Affymetrix Data</div>

        <table>
            <tr>
                <th>Affymetrix Name</th>
                <th>Download</th>
            </tr>
            {% for affymetrix in affymetrix_list %}
            <tr>
                <td id="tag-name-summary"><a href="{% url "data:affymetrix_detail" affymetrix.pk %}"> {{ affymetrix.name }} </a></td>
                <td id="tag-value"><a href="{% url "data:affymetrix_download" affymetrix.pk %}"> Download </a></td>
            </tr>
            {% empty %}
            <tr>
                <td id="tag-name"> Nothing found... </td>
            </tr>
            {% endfor %}
        </table>

        <table>
            <tr>
                <td>
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                
                            <span class="current">
                                Page {{ page_obj.number }} of {{ paginator.num_pages }}
                            </span>
                
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                </td>
            </tr>
        </table>
        <form action="{% url 'data:affymetrix_all_list' pk %}">
            <div class="page-search">
                <input type="number" name="page" min="1" max="{{ paginator.num_pages }}" value="{{ page }}">
                <input id='form-submit' type="submit" value="GO" />                                        
            </div>
        </form>
        <div id="hidden-line-bottom"></div>

    </div>
{% endblock %}
<!-- END CONTENT -->

22q11-ibbc/templates/data/data_documents.html
{% extends "base_private.html" %}

{% block title %}22q11-ibbc.org | Documents{% endblock title %}

<!-- CONTENT -->
{% block content %}
<div id='content-main'>

    <div id='content-data-menu'>
        <div id='content-data-menu-top'></div>
        <ul class="subNav">
            <li><a href="{% url 'data:documents_1' %}">Approved Ancillary Studies</a></li> |
            <li><a href="{% url 'data:documents_2' %}">Approved Proposals</a></li> |
            <li><a href="{% url 'data:documents_3' %}">Forms</a></li> |
            <li><a href="{% url 'data:documents_4' %}">General Meeting Minutes</a></li> |
            <li><a href="{% url 'data:documents_5' %}">Upcoming Meetings</a></li>
        </ul>
    </div>
    
    <div id='content-data-content'>
        {% block content-data-content %}{% endblock content-data-content %}
    </div>

</div>
{% endblock %}
<!-- END CONTENT -->

22q11-ibbc/templates/data/data_login.html
{% extends "base_private.html" %}

{% block title %}22q11-ibbc.org | Login{% endblock title %}

{% load staticfiles%}

<!-- CONTENT -->
{% block content %}
<div id="content">

    {% if form.errors %}
    <div id="dialog" title="Error">
        <p>Your username and password didn't match. Please try again.</p>
    </div>   
    {% endif %}
    
    <form method="post" action="{% url 'data:django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <div id='content-main-login'>
            <h1>Sign in</h1>

            <input id="id_username" maxlength="254" size="40" name="username" type="text" placeholder="Username"/>
            </br>
            <input id="id_password" name="password" size="40" type="password" placeholder="Password"/>
            </br>
            <input id='content-main-login-submit' type="submit" value="Login" />
            {% if next == '' %}
            <input type="hidden" name="next" value="/data" />
            {% else %}
            <input type="hidden" name="next" value="{{ next }}" />
            {% endif %}
            </br>
            <p><a href="{% url 'data:reset' %}">forgot password?</a></p>
        </div>
    </form>

</div>
{% endblock %}

22q11-ibbc/templates/data/data_password_reset_complete.html
{% extends "base_private.html" %}

{% block title %}22q11-ibbc.org | Password Reset{% endblock title %}

{% load staticfiles%}

<!-- CONTENT -->
{% block content %}
<div id="content">

    <div id='content-main-reset'>
        <h1>Password Reset</h1>
        <p>Your password has been set!  You may go ahead and log in now.</p>
        <p><a href="{% url 'data:22q11_ibbc_login' %}">Log in</a></p>
    </div>

</div>
{% endblock %}

22q11-ibbc/templates/data/data_password_reset_email.html
You're receiving this email because you requested a password reset for your user account at 22q11-ibbc.org

Please go to the following page and choose a new password:
{% block reset_link %}
https://22q11-ibbc.org{% url 'data:reset_confirm' uidb64=uid token=token %}
{% endblock %}
Your username, in case you've forgotten: "{{ user.get_username }}"

Thanks for using our site!

The 22q11-ibbc.org Admin

22q11-ibbc/templates/data/data_password_reset_form.html
{% extends "base_private.html" %}

{% block title %}22q11-ibbc.org | Password Reset{% endblock title %}

{% load staticfiles%}

<!-- CONTENT -->
{% block content %}
<div id="content">

    <div id='content-main-reset'>
        <h1>Password Reset</h1>

        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
    
        <form method="post">
            {% csrf_token %}
            {{ form.email.errors }}
            <input id="id_email" maxlength="254" name="email" type="email" placeholder="EMail" />
            <input type="submit" value="Reset my password" />
        </form>
    </div>
</div>
{% endblock %}

22q11-ibbc/templates/data/data_site_detail.html
{% extends "data/data_base.html" %}

<!-- CONTENT-DATA-CONTENT -->
{% block content-data-content %}
    <div id='data-box'>
        <div id='data-box-top'></div>
        <div id='data-box-title'>Site Detail</div>

        <table>
            <tr>
                <td class="tag-name"> Site Name </td><td class="tag-value"> {{ site.name }} </td>
            </tr>
            <tr>
                <td class="tag-name"> Site Group </td><td class="tag-value"> {{ site.group }} </td>
            </tr>
            <tr>
                <td class="tag-name"> Site PIs </td>
                <td>
                    <table class="inner-table">
                        {% for pi in site.site_pis.all %}
                            <tr>
                                <td class="tag-value"> <a href={% url "data:user_profile_detail" pi.pk %}>{{ pi.first_name }} {{ pi.last_name }}</a> </td>
                            </tr>
                        {% endfor %}
                    </table>
                </td>
            </tr>
            <tr>
                <td class="tag-name"> Site Members </td>
                <td>
                    <table class="inner-table">
                        {% for member in site.site_members.all %}
                            <tr>
                                <td class="tag-value"> <a href={% url "data:user_profile_detail" member.pk %}>{{ member.first_name }} {{ member.last_name }}</a> </td>
                            </tr>
                        {% endfor %}
                    </table>
                </td>
            </tr>
            <tr>
                <td class="tag-name"> Allowed Users </td>
                <td>
                    <table class="inner-table">
                        {% for allowed_user in site.allowed_users.all %}
                            <tr>
                                <td class="tag-value"> <a href={% url "data:user_profile_detail" allowed_user.pk %}>{{ allowed_user.first_name }} {{ allowed_user.last_name }}</a> </td>
                            </tr>
                        {% endfor %}
                    </table>
                </td>
            </tr>
            <tr>
                <td class="tag-name"> Site Subjects </td><td class="tag-value"><a href="{% url "data:subject_site_list" site.pk %}"> {{ subjects|get_item:site.name }}</a> subjects</td>
            </tr>
            <tr>
                <td class="tag-name"> Site Affymetrix </td><td class="tag-value"><a href="{% url "data:affymetrix_site_list" site.pk %}"> {{ affymetrixes|get_item:site.name }}</a> affymetrix data</td>
            </tr>
            <tr>
                <td class="tag-name"> Affymetrix Data Folder </td><td class="tag-value"><a href="{% url "data:affymetrix_folder_download" site.folder site.pk %}"> Download </a> </td>
            </tr>
        </table>

    </div>
{% endblock %}
<!-- END CONTENT -->

22q11-ibbc/templates/data/data_subject_list_all.html
{% extends "data/data_base.html" %}

<!-- CONTENT-DATA-CONTENT- -->
{% block content-data-content %}
    <div id='data-box'>
        <div id='data-box-top'></div>
        <div id='data-box-title'>List of subjects</div>

        <table>
            <tr>
                <th>Genomics DB ID</th>
                <th>Local Site ID</th>
                <th>Alias</th>
                <th>Project</th>
                <th>Site</th>
            </tr>
            {% for subject in subject_list %}
            <tr>
                <td id="tag-name"><a href="{% url "data:subject_detail" subject.pk %}"> {{ subject.pk }} </a></td>
                <td id="tag-value">{{ subject.site_id }}</td>
                <td id="tag-value">{{ subject.alias }}</td>
                <td id="tag-value">{{ subject.project }}</td>
                <td id="tag-value"><a href="{% url "data:site_detail" subject.owner_site.pk %}"> {{ subject.owner_site.name }} </a></td>
            </tr>
            {% empty %}
            <tr>
                <td id="tag-name"> Nothing found... </td>
            </tr>
            {% endfor %}
        </table>

        <table>
            <tr>
                <td>
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                
                            <span class="current">
                                Page {{ page_obj.number }} of {{ paginator.num_pages }}
                            </span>
                
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                </td>
            </tr>
        </table>
        <form action="{% url 'data:subject_all_list' %}">
            <div class="page-search">
                <input type="number" name="page" min="1" max="{{ paginator.num_pages }}" value="{{ page }}">
                <input id='form-submit' type="submit" value="GO" />                                        
            </div>
        </form>
        <div id="hidden-line-bottom"></div>

    </div>
{% endblock %}
<!-- END CONTENT -->

22q11-ibbc/templates/data/data_subject_list_form_search.html
{% extends "data/data_base.html" %}

<!-- CONTENT-DATA-CONTENT- -->
{% block content-data-content %}
    <div id='data-box'>
        <div id='data-box-top'></div>
        <div id='data-box-title'>Search subjects</div>

        <form method="post" action="">
            {% csrf_token %}
            <table id='form-detail-table'>
            <tbody>
                <tr>
                    <th>Genomic DB ID:</th>
                    <td><input id="id_genomic_db_id" maxlength="50" name="genomic_db_id" type="number" value="{{ form.genomic_db_id.value|default_if_none:"" }}"/></td>
                </tr>
                <tr>
                    <th>Local Site ID:</th>
                    <td><input id="id_local_id" maxlength="50" name="local_id" type="text" value="{{ form.local_id.value|default_if_none:"" }}"/></td> 
                </tr>
                <tr>
                    <th>Alias:</th>
                    <td><input id="id_alias" maxlength="50" name="alias" type="text" value="{{ form.alias.value|default_if_none:"" }}"/></td> 
                </tr>
                <tr>
                    <th>Site:</th>
                    <td>                
                        <select id="id_site" name="site">
                        {% for x,y in form.fields.site.choices %}
                            <option value="{{ x }}">{{ y }}</option>
                        {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <th></th>
                    <td><input id='form-submit' type="submit" value="Submit" /></td>
                </tr>    
                <tr>
                    <th></th>
                    <td><a href="{% url 'data:subject_search' %}">Cancel</a></td>
                </tr>
            </tbody>
            </table>
        </form>

    </div>
{% endblock %}
<!-- END CONTENT -->

22q11-ibbc/templates/data/data_subject_list_site.html
{% extends "data/data_base.html" %}

<!-- CONTENT-DATA-CONTENT- -->
{% block content-data-content %}
    <div id='data-box'>
        <div id='data-box-top'></div>
        <div id='data-box-title'>List of subjects</div>

        <table>
            <tr>
                <th>Genomics DB ID</th>
                <th>Local Site ID</th>
                <th>Alias</th>
                <th>Project</th>
                <th>Site</th>
            </tr>
            {% for subject in subject_list %}
            <tr>
                <td id="tag-name"><a href="{% url "data:subject_detail" subject.pk %}"> {{ subject.pk }} </a></td>
                <td id="tag-value">{{ subject.site_id }}</td>
                <td id="tag-value">{{ subject.alias }}</td>
                <td id="tag-value">{{ subject.project }}</td>
                <td id="tag-value"><a href="{% url "data:site_detail" subject.owner_site.pk %}"> {{ subject.owner_site.name }} </a></td>
            </tr>
            {% empty %}
            <tr>
                <td id="tag-name"> Nothing found... </td>
            </tr>
            {% endfor %}
        </table>

        <table>
            <tr>
                <td>
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                
                            <span class="current">
                                Page {{ page_obj.number }} of {{ paginator.num_pages }}
                            </span>
                
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                </td>
            </tr>
        </table>
        <form action="{% url 'data:subject_site_list' pk %}">
            <div class="page-search">
                <input type="number" name="page" min="1" max="{{ paginator.num_pages }}" value="{{ page }}">
                <input id='form-submit' type="submit" value="GO" />                                        
            </div>
        </form>
        <div id="hidden-line-bottom"></div>

    </div>
{% endblock %}
<!-- END CONTENT -->

22q11-ibbc/templates/data/data_wgs.html
{% extends "data/data_base.html" %}

<!-- CONTENT-DATA-CONTENT- -->
{% block content-data-content %}
    <div id='data-box'>
        <div id='data-box-top'></div>
        <div id='data-box-title'>Whole Genome Sequencing Files</div>
        
        <table class="detail-table">
            <tr>
                <td id="announcement">The following data are generated by the Cutler lab at Emory, please contact
                David Cutler at djcutle [at] emory.edu</td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" '22q_batch1.hh.gz' %}">22q_batch1.hh.gz </a></td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" '22q_batch1.log.gz' %}">22q_batch1.log.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" '22q_batch1.vcf.gz' %}">22q_batch1.vcf.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" 'first_100.bed.gz' %}">first_100.bed.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" 'first_100.bim.gz' %}">first_100.bim.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" 'first_100.fam.gz' %}">first_100.fam.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" 'first_100.hh.gz' %}">first_100.hh.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" 'first_100.log.gz' %}">first_100.log.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" 'first_100.map.gz' %}">first_100.map.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" 'first_100.ped.gz' %}">first_100.ped.gz </a> </td>
            </tr>
            <tr>
                <td id="tag-name"><a href="{% url "data:wgs_download" 'snps.annotations.txt.gz' %}">snps.annotations.txt.gz </a> </td>
            </tr>
        </table>

    </div>
{% endblock %}
<!-- END CONTENT -->